# Generated by Django 3.0.6 on 2020-05-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('profile_bio', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='')),
                ('total_friends', models.IntegerField()),
            ],
        ),
    ]
